---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    package:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages
    apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
