- name: install apache and php for Ubuntu servers
  tags: apache,php
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start apache (not needed on Ubuntu)
  tags: apache
  vars: 
    package_name: apache2
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: copy default html file
  tags: apache
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  notify: restart_apache

